### PR TITLE
Add hibernate functionality

### PR DESCRIPTION
**Pull request by padawarmik**
Hi, 
Following PR is adding the Hibernate (save to disk) functionality.
I have tested it on my local instance and it works fine. 
If you have any suggestions please let me know!

### CODE REVIEW

**Comment by dougiteixeira** [comment]
Can you point out where this is documented to verify the implication across the various versions of Proxmox?

**Review by dougiteixeira — CHANGES_REQUESTED** [review]
Can you point out where this is documented to verify the implication across the various versions of Proxmox?

**Comment by padawarmik** [comment]
Sure, it's documented under the suspend option as "todisk":
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/status/suspend[](url)

**Comment by dougiteixeira** [comment]
> Sure, it's documented under the suspend option as "todisk":
> [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/status/suspend](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/%7Bnode%7D/qemu/%7Bvmid%7D/status/suspend)

Let's move on to add that.

Please can you update the branch to the latest version and add `key_translate` and entity name in `strings.json` and `translations/en.json`.

**Comment by padawarmik** [comment]
Done. You can review the changes I have made.

**Review by dougiteixeira — APPROVED** [review]

**Comment by dougiteixeira** [comment]
Thanks @padawarmik!

**Pull request merged**
