### PR TITLE
Add config option for update information

### LINKED ISSUE #334: Sys.modify authorization
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

When I restart Home Assistant I find this error message:

____
L'utente hass@pve non ha le autorizzazioni sufficienti per accedere alla risorsa {resource}.

Suggerimento sui permessi necessari:

    ['perm','/nodes/Update proxmox',['Sys.Modify']]

Si prega di consultare la documentazione e verificare le autorizzazioni dell'utente..
____

I close the error and it seems to work fine until the next restart of Home Assistant

Screenshot 2024-07-07 alle 16 59 57

to configure proxmox within Home Assistant I followed the official guide, and until some time ago the error did not exist.

### In which version of Home Assistant Core do you have the problem?

2024.7.1

### What version of Proxmox VE Custom Integration has the issue?

3.4.4

### What version of Proxmox VE do you have the problem?

8.2.2

### Diagnostics information

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by uneart**
Fixes #334

Proposal for an additional option to disable the update information coordinator. This would fix repair warnings for users not willing to give `Sys.Modify` permissions to the Proxmox user/group.

@dougiteixeira please review if this goes into the right direction from your point of view.

I tested this on my staging Home Assistant instance and it seems to work as expected.

### Open tasks
- [x] Translation EN
- [x] Testing
- [x] Docs / changelog

### CODE REVIEW

**Comment by Sab44** [comment]
Thanks a lot for taking care of this issue!
I tested your changes, the repair issue is no longer showing up 👍 
However there seems to be a small issue with the strings in the config flow, where "update_enabled" is using the key rather than the value to display text, see attached screenshot:
Screenshot 2024-11-29 at 10 38 56
Again thanks, and let's hope we can get it merged into the integration!

**Comment by Sab44** [comment]
HA is in english. All the other strings on this form appear fine.
I noticed that in the `en.json` you don't have the `update_enable` string after line 23 and 26. But tbh even after adding them there it still didn't show up for me...

**Comment by Sab44** [comment]
Hey @uneart it's showing up properly now 👍 
Good job. @dougiteixeira if you could take a look at this it'd be appreciated. Thanks!

**Comment by dougiteixeira** [comment]
This implementation is not complete, let me think and see if another approach works. In the next few weeks I will come back with a definitive solution.

Thanks!

**Comment by dougiteixeira** [comment]
The code to ignore the missing permission repair has been fixed. I think it is simpler and more practical for the user than adding another configuration option.

Previously, even ignoring the repair would reappear after restarting or reloading the integration. This has now been fixed.

**Pull request closed without merging**
